version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - org.jetbrains.kotlin*
          - org.jetbrains.compose*
        update-types:
          - minor
          - patch
      compose:
        patterns:
          - androidx.compose*
          - org.jetbrains.compose*
        update-types:
          - minor
          - patch
      room:
        patterns:
          - androidx.room*
        update-types:
          - minor
          - patch
      koin:
        patterns:
          - io.insert-koin*
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
