domain:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/*'
          - 'androidApp/src/**/*'

ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/ui/src/**/*'

habits:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/habits/**/*'
          - 'shared/ui/src/**/habit/**/*'
          - 'androidApp/src/**/habits/**/*'

tasks:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/tasks/**/*'
          - 'shared/ui/src/**/task/**/*'
          - 'androidApp/src/**/tasks/**/*'

pomodoro:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/tasks/Pomodoro*'
          - 'shared/ui/src/**/task/**/Pomodoro*'
          - 'androidApp/src/**/tasks/**/Pomodoro*'
          - 'androidApp/src/**/pomodoroalarm/**/*'

settings:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/settings/**/*'
          - 'shared/ui/src/**/setting/**/*'
          - 'androidApp/src/**/core/data/datastore/**/*'

theme:
  - changed-files:
      - any-glob-to-any-file:
          - 'shared/core/src/commonMain/**/theme/**/*'
          - 'shared/ui/src/**/theme/**/*'

widgets:
  - changed-files:
      - any-glob-to-any-file:
          - 'androidApp/src/**/widgets/**/*'

deps:
  - changed-files:
      - any-glob-to-any-file:
          - 'gradle/**/*'
          - 'build.gradle.kts'
          - 'settings.gradle.kts'
          - 'gradle.properties'
          - 'libs.versions.toml'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
